# Generated by Django 4.0.5 on 2022-06-02 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab4_191001_application', '0002_rename_hobbies_profile_interests_remove_profile_age_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='PostFile',
        ),
    ]
