# Generated by Django 4.0.5 on 2022-06-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab4_191001_application', '0004_alter_postfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
