# Generated by Django 4.0.5 on 2022-06-02 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab4_191001_application', '0005_alter_postfile_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostFile',
        ),
    ]
